//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v13.7.2+fd5b8de
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace UmbracoHeadlessBFF.SharedModules.Umbraco.Models.ModelsBuilder
{
	/// <summary>Not Found</summary>
	[PublishedModel("notFound")]
	public partial class NotFound : PublishedContentModel, IPageContent, ISeoSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "")]
		public new const string ModelTypeAlias = "notFound";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<NotFound, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public NotFound(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Main Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mainContent")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockGridModel MainContent => global::UmbracoHeadlessBFF.SharedModules.Umbraco.Models.ModelsBuilder.PageContent.GetMainContent(this, _publishedValueFallback);

		///<summary>
		/// Description: Description to show on search engine results
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("metaDescription")]
		public virtual string MetaDescription => global::UmbracoHeadlessBFF.SharedModules.Umbraco.Models.ModelsBuilder.SeoSettings.GetMetaDescription(this, _publishedValueFallback);

		///<summary>
		/// Image: Image to show on search engine results
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("metaImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops MetaImage => global::UmbracoHeadlessBFF.SharedModules.Umbraco.Models.ModelsBuilder.SeoSettings.GetMetaImage(this, _publishedValueFallback);

		///<summary>
		/// Title: Title to show on search engine results
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("metaTitle")]
		public virtual string MetaTitle => global::UmbracoHeadlessBFF.SharedModules.Umbraco.Models.ModelsBuilder.SeoSettings.GetMetaTitle(this, _publishedValueFallback);

		///<summary>
		/// Description: Optional description override for open graph / sharing link to page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ogDescription")]
		public virtual string OgDescription => global::UmbracoHeadlessBFF.SharedModules.Umbraco.Models.ModelsBuilder.SeoSettings.GetOgDescription(this, _publishedValueFallback);

		///<summary>
		/// Image: Optional image override for open graph / sharing link to page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ogImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops OgImage => global::UmbracoHeadlessBFF.SharedModules.Umbraco.Models.ModelsBuilder.SeoSettings.GetOgImage(this, _publishedValueFallback);

		///<summary>
		/// Title: Optional title override for open graph / sharing link to page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ogTitle")]
		public virtual string OgTitle => global::UmbracoHeadlessBFF.SharedModules.Umbraco.Models.ModelsBuilder.SeoSettings.GetOgTitle(this, _publishedValueFallback);

		///<summary>
		/// Type: What type of content does this page contain
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ogType")]
		public virtual string OgType => global::UmbracoHeadlessBFF.SharedModules.Umbraco.Models.ModelsBuilder.SeoSettings.GetOgType(this, _publishedValueFallback);

		///<summary>
		/// Index Options: Options to signal to crawlers, no options selected = allow everything
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("robotsIndexOptions")]
		public virtual global::System.Collections.Generic.List<string> RobotsIndexOptions => global::UmbracoHeadlessBFF.SharedModules.Umbraco.Models.ModelsBuilder.SeoSettings.GetRobotsIndexOptions(this, _publishedValueFallback);

		///<summary>
		/// Unavailable After: Optionally, do not show this page after selected date/time
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "")]
		[ImplementPropertyType("robotsUnavailableAfter")]
		public virtual global::System.DateTime RobotsUnavailableAfter => global::UmbracoHeadlessBFF.SharedModules.Umbraco.Models.ModelsBuilder.SeoSettings.GetRobotsUnavailableAfter(this, _publishedValueFallback);

		///<summary>
		/// Change Frequency: How often the page changes main content  (Ignored by Google)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sitemapChangeFrequency")]
		public virtual string SitemapChangeFrequency => global::UmbracoHeadlessBFF.SharedModules.Umbraco.Models.ModelsBuilder.SeoSettings.GetSitemapChangeFrequency(this, _publishedValueFallback);

		///<summary>
		/// Last Modified Overwrite: Optional override to using the page's last modified/published date from Umbraco
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "")]
		[ImplementPropertyType("sitemapLastModifiedOverwrite")]
		public virtual global::System.DateTime SitemapLastModifiedOverwrite => global::UmbracoHeadlessBFF.SharedModules.Umbraco.Models.ModelsBuilder.SeoSettings.GetSitemapLastModifiedOverwrite(this, _publishedValueFallback);

		///<summary>
		/// Priority: How much priority this page has in the whole of the site  (Ignored by Google)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "")]
		[ImplementPropertyType("sitemapPriority")]
		public virtual decimal SitemapPriority => global::UmbracoHeadlessBFF.SharedModules.Umbraco.Models.ModelsBuilder.SeoSettings.GetSitemapPriority(this, _publishedValueFallback);

		///<summary>
		/// Show On Sitemap: Show this page on the sitemap
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "")]
		[ImplementPropertyType("sitemapShow")]
		public virtual bool SitemapShow => global::UmbracoHeadlessBFF.SharedModules.Umbraco.Models.ModelsBuilder.SeoSettings.GetSitemapShow(this, _publishedValueFallback);
	}
}
