//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace UmbracoHeadlessBFF.Cms.Modules.Common.Umbraco.Models
{
	/// <summary>Blog Repository</summary>
	[PublishedModel("blogRepository")]
	public partial class BlogRepository : PublishedContentModel, INavigationSettings, IRedirectSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "")]
		public new const string ModelTypeAlias = "blogRepository";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<BlogRepository, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public BlogRepository(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Breadcrumb Name Override: Override breadcrumb shown (empty = name of page)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("breadcrumbNameOverride")]
		public virtual string BreadcrumbNameOverride => global::UmbracoHeadlessBFF.Cms.Modules.Common.Umbraco.Models.NavigationSettings.GetBreadcrumbNameOverride(this, _publishedValueFallback);

		///<summary>
		/// Show Breadcrumb Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "")]
		[ImplementPropertyType("showBreadcrumbLink")]
		public virtual bool ShowBreadcrumbLink => global::UmbracoHeadlessBFF.Cms.Modules.Common.Umbraco.Models.NavigationSettings.GetShowBreadcrumbLink(this, _publishedValueFallback);

		///<summary>
		/// Show Breadcrumbs: Show breadcrumb chain for page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "")]
		[ImplementPropertyType("showBreadcrumbs")]
		public virtual bool ShowBreadcrumbs => global::UmbracoHeadlessBFF.Cms.Modules.Common.Umbraco.Models.NavigationSettings.GetShowBreadcrumbs(this, _publishedValueFallback);

		///<summary>
		/// Show In Breadcrumbs: Show this page's breadcrumb in other pages
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "")]
		[ImplementPropertyType("showInBreadcrumbs")]
		public virtual bool ShowInBreadcrumbs => global::UmbracoHeadlessBFF.Cms.Modules.Common.Umbraco.Models.NavigationSettings.GetShowInBreadcrumbs(this, _publishedValueFallback);

		///<summary>
		/// Redirect Direction: Find and redirect to first page that is "viewable" in the direction selected
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "")]
		[ImplementPropertyType("redirectDirection")]
		public virtual global::UmbracoHeadlessBFF.SharedModules.Common.Cms.DeliveryApi.Models.Data.RedirectFallbackDirection RedirectDirection => global::UmbracoHeadlessBFF.Cms.Modules.Common.Umbraco.Models.RedirectSettings.GetRedirectDirection(this, _publishedValueFallback);

		///<summary>
		/// Redirect Link: Direct link to a page, url, etc
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("redirectLink")]
		public virtual global::Umbraco.Cms.Core.Models.Link RedirectLink => global::UmbracoHeadlessBFF.Cms.Modules.Common.Umbraco.Models.RedirectSettings.GetRedirectLink(this, _publishedValueFallback);
	}
}
